### ISSUE TITLE
cpu inference

### ISSUE THREAD

**Issue by AK391** [YuanxunLu/LiveSpeechPortraits#14]
please add option for cpu inference in demo.py

**Comment by AK391** [comment]
@YuanxunLu thanks i still get this error when using --device cpu

Traceback (most recent call last):
  File "demo.py", line 27, in <module>
    from funcs import utils
  File "/content/LiveSpeechPortraits/funcs/utils.py", line 60, in <module>
    n_mel_channels=80, mel_fmin=90, mel_fmax=7600.0).cuda()
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 637, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 573, in _apply
    self._buffers[key] = fn(buf)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 637, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python3.7/dist-packages/torch/cuda/__init__.py", line 172, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available

**Comment by YuanxunLu** [comment]
Thanks for your feedback. I've modified the functions and please the lateset version.

**Comment by AK391** [comment]
@YuanxunLu thanks i am getting this error now

Traceback (most recent call last):
  File "demo.py", line 130, in <module>
    Featopt = FeatureOptions().parse() 
  File "/content/LiveSpeechPortraits/options/base_options_audio2feature.py", line 158, in parse
    torch.cuda.set_device(opt.gpu_ids[0])
  File "/usr/local/lib/python3.7/dist-packages/torch/cuda/__init__.py", line 264, in set_device
    torch._C._cuda_setDevice(device)
  File "/usr/local/lib/python3.7/dist-packages/torch/cuda/__init__.py", line 172, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available

**Comment by YuanxunLu** [comment]
I‘ve commented these codes in the latest version. Check it if it has any questions.

**Comment by wanghaisheng** [comment]
@YuanxunLu    
pls change these code and then cpu inference can work 
FYI  pytorch cpu version is required

1.lossess.py
    # return  current_sample.reshape(b, T, -1).cuda()
    return  current_sample.reshape(b, T, -1)
2.demo.py



if torch.cuda.is_available():
    map_location=lambda storage, loc: storage.cuda()
else:
    map_location='cpu'
    

APC_model.load_state_dict(torch.load(config['model_params']['APC']['ckp_path'],map_location=map_location), strict=False)
