### ISSUE TITLE
ModuleNotFoundError: No module named 'numba.decorators'

### ISSUE THREAD

**Issue by Robertsmania** [YuanxunLu/LiveSpeechPortraits#75]
I get the following error trying to execute the demo.  Searching on the error I find suggestions for changing the numba/librosa versions but would appreciate guidance for this project.

(LSP) C:\Users\Kris\source\repos\LiveSpeechPortraits>python demo.py --id May --driving_audio .\data\Input\00083.wav --device cuda
Traceback (most recent call last):
  File "demo.py", line 8, in <module>
    import librosa
  File "C:\Users\Kris\anaconda3\envs\LSP\lib\site-packages\librosa\__init__.py", line 13, in <module>
    from . import core
  File "C:\Users\Kris\anaconda3\envs\LSP\lib\site-packages\librosa\core\__init__.py", line 114, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "C:\Users\Kris\anaconda3\envs\LSP\lib\site-packages\librosa\core\time_frequency.py", line 10, in <module>
    from ..util.exceptions import ParameterError
  File "C:\Users\Kris\anaconda3\envs\LSP\lib\site-packages\librosa\util\__init__.py", line 73, in <module>
    from . import decorators
  File "C:\Users\Kris\anaconda3\envs\LSP\lib\site-packages\librosa\util\decorators.py", line 9, in <module>
    from numba.decorators import jit as optional_jit
ModuleNotFoundError: No module named 'numba.decorators'

We followed the README instructions for the LSP environment, instaled PyTorch 1.7 and the requirements like so:

conda install pytorch==1.7.0 torchvision==0.8.0 torchaudio==0.7.0 cudatoolkit=9.2 -c pytorch
pip install -r requirements.txt

Here are the versions of the packages:

Requirement already satisfied: tqdm in c:\users\kris\anaconda3\envs\lsp\lib\site-packages (from -r requirements.txt (line 1)) (4.64.0)
Requirement already satisfied: librosa==0.7.0 in c:\users\kris\anaconda3\envs\lsp\lib\site-packages (from -r requirements.txt (line 2)) (0.7.0)
Requirement already satisfied: scikit_image in c:\users\kris\anaconda3\envs\lsp\lib\site-packages (from -r requirements.txt (line 3)) (0.17.2)
Requirement already satisfied: opencv_python==4.4.0.40 in c:\users\kris\anaconda3\envs\lsp\lib\site-packages (from -r requirements.txt (line 4)) (4.4.0.40)
Requirement already satisfied: scipy in c:\users\kris\anaconda3\envs\lsp\lib\site-packages (from -r requirements.txt (line 5)) (1.5.4)
Requirement already satisfied: dominate in c:\users\kris\anaconda3\envs\lsp\lib\site-packages (from -r requirements.txt (line 6)) (2.7.0)
Requirement already satisfied: albumentations==0.5.2 in c:\users\kris\anaconda3\envs\lsp\lib\site-packages (from -r requirements.txt (line 7)) (0.5.2)
Requirement already satisfied: numpy in c:\users\kris\anaconda3\envs\lsp\lib\site-packages (from -r requirements.txt (line 8)) (1.19.2)
Requirement already satisfied: beautifulsoup4 in c:\users\kris\anaconda3\envs\lsp\lib\site-packages (from -r requirements.txt (line 9)) (4.11.1)
Requirement already satisfied: decorator>=3.0.0 in c:\users\kris\anaconda3\envs\lsp\lib\site-packages (from librosa==0.7.0->-r requirements.txt (line 2)) (4.4.2)
Requirement already satisfied: soundfile>=0.9.0 in c:\users\kris\anaconda3\envs\lsp\lib\site-packages (from librosa==0.7.0->-r requirements.txt (line 2)) (0.10.3.post1)
Requirement already satisfied: six>=1.3 in c:\users\kris\anaconda3\envs\lsp\lib\site-packages (from librosa==0.7.0->-r requirements.txt (line 2)) (1.16.0)
Requirement already satisfied: numba>=0.38.0 in c:\users\kris\anaconda3\envs\lsp\lib\site-packages (from librosa==0.7.0->-r requirements.txt (line 2)) (0.53.1)
Requirement already satisfied: scikit-learn!=0.19.0,>=0.14.0 in c:\users\kris\anaconda3\envs\lsp\lib\site-packages (from librosa==0.7.0->-r requirements.txt (line 2)) (0.24.2)
Requirement already satisfied: resampy>=0.2.0 in c:\users\kris\anaconda3\envs\lsp\lib\site-packages (from librosa==0.7.0->-r requirements.txt (line 2)) (0.4.0)
Requirement already satisfied: joblib>=0.12 in c:\users\kris\anaconda3\envs\lsp\lib\site-packages (from librosa==0.7.0->-r requirements.txt (line 2)) (1.1.0)
Requirement already satisfied: audioread>=2.0.0 in c:\users\kris\anaconda3\envs\lsp\lib\site-packages (from librosa==0.7.0->-r requirements.txt (line 2)) (3.0.0)
Requirement already satisfied: opencv-python-headless>=4.1.1 in c:\users\kris\anaconda3\envs\lsp\lib\site-packages (from albumentations==0.5.2->-r requirements.txt (line 7)) (4.6.0.66)
Requirement already satisfied: PyYAML in c:\users\kris\anaconda3\envs\lsp\lib\site-packages (from albumentations==0.5.2->-r requirements.txt (line 7)) (6.0)
Requirement already satisfied: imgaug>=0.4.0 in c:\users\kris\anaconda3\envs\lsp\lib\site-packages (from albumentations==0.5.2->-r requirements.txt (line 7)) (0.4.0)
Requirement already satisfied: importlib-resources in c:\users\kris\anaconda3\envs\lsp\lib\site-packages (from tqdm->-r requirements.txt (line 1)) (5.4.0)
Requirement already satisfied: colorama in c:\users\kris\anaconda3\envs\lsp\lib\site-packages (from tqdm->-r requirements.txt (line 1)) (0.4.5)
Requirement already satisfied: imageio>=2.3.0 in c:\users\kris\anaconda3\envs\lsp\lib\site-packages (from scikit_image->-r requirements.txt (line 3)) (2.15.0)
Requirement already satisfied: pillow!=7.1.0,!=7.1.1,>=4.3.0 in c:\users\kris\anaconda3\envs\lsp\lib\site-packages (from scikit_image->-r requirements.txt (line 3)) (8.4.0)
Requirement already satisfied: tifffile>=2019.7.26 in c:\users\kris\anaconda3\envs\lsp\lib\site-packages (from scikit_image->-r requirements.txt (line 3)) (2020.9.3)
Requirement already satisfied: matplotlib!=3.0.0,>=2.0.0 in c:\users\kris\anaconda3\envs\lsp\lib\site-packages (from scikit_image->-r requirements.txt (line 3)) (3.3.4)
Requirement already satisfied: PyWavelets>=1.1.1 in c:\users\kris\anaconda3\envs\lsp\lib\site-packages (from scikit_image->-r requirements.txt (line 3)) (1.1.1)
Requirement already satisfied: networkx>=2.0 in c:\users\kris\anaconda3\envs\lsp\lib\site-packages (from scikit_image->-r requirements.txt (line 3)) (2.5.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\kris\anaconda3\envs\lsp\lib\site-packages (from beautifulsoup4->-r requirements.txt (line 9)) (2.3.2.post1)
Requirement already satisfied: Shapely in c:\users\kris\anaconda3\envs\lsp\lib\site-packages (from imgaug>=0.4.0->albumentations==0.5.2->-r requirements.txt (line 7)) (1.8.2)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\users\kris\anaconda3\envs\lsp\lib\site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit_image->-r requirements.txt (line 3)) (3.0.9)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\kris\anaconda3\envs\lsp\lib\site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit_image->-r requirements.txt (line 3)) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\kris\anaconda3\envs\lsp\lib\site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit_image->-r requirements.txt (line 3)) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\kris\anaconda3\envs\lsp\lib\site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit_image->-r requirements.txt (line 3)) (0.11.0)
Requirement already satisfied: setuptools in c:\users\kris\anaconda3\envs\lsp\lib\site-packages (from numba>=0.38.0->librosa==0.7.0->-r requirements.txt (line 2)) (58.0.4)
Requirement already satisfied: llvmlite<0.37,>=0.36.0rc1 in c:\users\kris\anaconda3\envs\lsp\lib\site-packages (from numba>=0.38.0->librosa==0.7.0->-r requirements.txt (line 2)) (0.36.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\kris\anaconda3\envs\lsp\lib\site-packages (from scikit-learn!=0.19.0,>=0.14.0->librosa==0.7.0->-r requirements.txt (line 2)) (3.1.0)
Requirement already satisfied: cffi>=1.0 in c:\users\kris\anaconda3\envs\lsp\lib\site-packages (from soundfile>=0.9.0->librosa==0.7.0->-r requirements.txt (line 2)) (1.15.1)
Requirement already satisfied: pycparser in c:\users\kris\anaconda3\envs\lsp\lib\site-packages (from cffi>=1.0->soundfile>=0.9.0->librosa==0.7.0->-r requirements.txt (line 2)) (2.21)
Requirement already satisfied: zipp>=3.1.0 in c:\users\kris\anaconda3\envs\lsp\lib\site-packages (from importlib-resources->tqdm->-r requirements.txt (line 1)) (3.6.0)

**Comment by mendynew** [comment]
install the lower version of numba
pip install numba==0.48.0

**Comment by iboyles** [comment]
Dang this doesn't work on colab as you can't install anything that low due to python version fixed at 3.10.10

**Comment by Robertsmania** [comment]
Even after getting past that numba error I had other issues and was never able to get it working.

It would be great if there was a refresh to the repository to get it up to date on the current versions of all the packages...

**Comment by iboyles** [comment]
lol use my makeittalk colab it works

**Comment by SD-Star-Liu** [comment]
See the same issue today, and takes forever time to solve package conflicts.....
